[flags]
basic = true
rate = "3s"

[cpu]
hide_avg_cpu = true

# processes widget configuration
[processes]
columns = ["pid", "User", "Name", "CPU%", "Mem%", "time"]
hide_k_threads = true
process_command = true
default_tree = true
default_sort = "pid"
