[flags]
basic = true
tree = true
# group_processes = true # incompatible with tree

hide_avg_cpu = true
rate = "3s"

# processes widget configuration
[processes]
columns = ["PID", "Name", "CPU%", "Mem%", "User", "State", "GMem%", "GPU%"]
